apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi-3
  name: fastapi-3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: fastapi
  type: LoadBalancer
