name: Docker Image CI

on:
  push:
    branches: [ "argocd" ]
  pull_request:
    branches: [ "argocd" ]
  workflow_dispatch:

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    
    - name: Build
      run: |-
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        docker build -t bala2805/fastapi:tlsv1 .
        
    - name: Publish
      run: |-
        docker push bala2805/fastapi:tlsv1
        docker rmi bala2805/fastapi:tlsv1
